# Generated by Django 4.1.7 on 2023-03-13 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('completed', models.BooleanField(default=False, verbose_name='Выполнено ли')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('deadline', models.DateTimeField(verbose_name='Крайний срок')),
            ],
        ),
    ]
